name: idt-mouse-brain-segmentation
channels:
  - conda-forge
dependencies:
  - black
  - ca-certificates
  - certifi
  - openssl
  - matplotlib
  - pandas=1.5
  - pip
  - python=3.9
  - rasterio=1.3
  - scikit-image=0.19
  - shapely=2.0
  - tqdm=4.64
  - pip:
    - bg-atlasapi==1.0.2
    - napari[all]==0.4.17
    - PyQt5>=5.12.3