name: mouse-brain-alignment-tool
channels:
  - conda-forge
dependencies:
  - black
  - ca-certificates
  - certifi
  - openssl
  - matplotlib
  - openpyxl==3.1.2
  - pandas=1.5
  - pip
  - python=3.9
  - rasterio=1.3
  - scikit-image=0.19
  - shapely=2.0
  - tqdm=4.64
  - pip:
    - bg-atlasapi==1.0.2
    # - napari[all]==0.4.17
    - git+https://github.com/napari/napari.git@0bc1adc290d50f9793bd1b7c0ce912095f2e2354#egg=napari[all]
    - PyQt5>=5.12.3